# -*- coding: utf-8 -*-
"""STREAMLIT-GITHUB-DATAPRESENT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RwQA3G1QciBb-3EjynVRH1TKEHNjXrgM
"""

# Install Streamlit if not already installed

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

st.title("Plotly Visualization Explorer")

# Dataset
data = {
    "year":[2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025],
    "avg_solve_time":[28,22,18,20,24,30,34,38,42,44,45],
    "best_solve_time":[18,16,14,15,17,19,21,23,25,27,28],
    "practice_hours":[400,350,300,200,120,80,60,40,25,15,10],
    "solves_per_year":[2000,1800,1500,1200,900,700,600,500,400,250,150],
    "sleep_hours":[8,8,7.5,7,7,6.5,6,6,6,5.5,5],
    "stress_level":[2,3,3,4,5,6,7,7,8,8,9],
    "caffeine_mg":[50,60,80,120,150,200,220,240,260,280,300],
    "social_media_hours":[0,0,0.5,2,3,3.5,4,4.5,5,5.5,6]
}

df = pd.DataFrame(data)

# Tabs
tab1, tab2, tab3 = st.tabs(["Charts", "Dataset", "Code"])

# --------------------
# Charts Tab
# --------------------
with tab1:

    chart = st.selectbox(
        "Select Chart Type",
        [
            "Line Chart",
            "Scatter Plot",
            "Bar Chart",
            "Histogram",
            "Box Plot",
            "Bubble Chart",
            "Heatmap",
            "Scatter Matrix"
        ]
    )

    if chart == "Line Chart":
        fig = px.line(df, x="year", y=["avg_solve_time","best_solve_time"], markers=True)
        st.plotly_chart(fig)

    elif chart == "Scatter Plot":
        fig = px.scatter(df, x="practice_hours", y="avg_solve_time", color="stress_level")
        st.plotly_chart(fig)

    elif chart == "Bar Chart":
        fig = px.bar(df, x="year", y="practice_hours")
        st.plotly_chart(fig)

    elif chart == "Histogram":
        fig = px.histogram(df, x="avg_solve_time", nbins=8)
        st.plotly_chart(fig)

    elif chart == "Box Plot":
        fig = px.box(df, y="avg_solve_time", points="all")
        st.plotly_chart(fig)

    elif chart == "Bubble Chart":
        fig = px.scatter(df, x="practice_hours", y="avg_solve_time",
                         size="solves_per_year", color="year", size_max=60)
        st.plotly_chart(fig)

    elif chart == "Heatmap":
        corr = df.corr()
        fig = go.Figure(data=go.Heatmap(
            z=corr.values,
            x=corr.columns,
            y=corr.columns,
            colorscale="RdBu"
        ))
        st.plotly_chart(fig)

    elif chart == "Scatter Matrix":
        fig = px.scatter_matrix(
            df,
            dimensions=[
                "avg_solve_time",
                "practice_hours",
                "stress_level",
                "sleep_hours",
                "social_media_hours"
            ]
        )
        st.plotly_chart(fig)

# --------------------
# Dataset Tab
# --------------------
with tab2:

    st.subheader("Rubik's Cube Performance Dataset")
    st.dataframe(df)

# --------------------
# Code Tab
# --------------------
with tab3:

    st.subheader("Example Plotly Code")

    st.code("""
fig = px.line(
    df,
    x="year",
    y=["avg_solve_time","best_solve_time"],
    markers=True
)
fig.show()
""")





